"""fk behaviour & names

Revision ID: b2b667f3c1d1
Revises: f48dbc4b1a55
Create Date: 2025-05-26 21:47:50.176674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b667f3c1d1'
down_revision: Union[str, None] = 'f48dbc4b1a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_logs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('habit_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_uuid'], ['habits.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('habits', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.add_column('habits', sa.Column('is_quantifiable', sa.Boolean(), nullable=False))
    op.add_column('habits', sa.Column('target_quantity', sa.Float(), nullable=True))
    op.add_column('habits', sa.Column('unit', sa.String(), nullable=True))
    op.drop_constraint('habits_user_id_fkey', 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('habits', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key('habits_user_id_fkey', 'habits', 'users', ['user_id'], ['uuid'])
    op.drop_column('habits', 'unit')
    op.drop_column('habits', 'target_quantity')
    op.drop_column('habits', 'is_quantifiable')
    op.drop_column('habits', 'user_uuid')
    op.drop_table('habit_logs')
    # ### end Alembic commands ###
